In [21]:
import torch
import torch_geometric.transforms as T
from torch_geometric.datasets import Planetoid

In [10]:
a = torch.floor(torch.randn(size=(10,1)))
a

tensor([[-2.],
        [-1.],
        [-2.],
        [ 0.],
        [-1.],
        [-2.],
        [-1.],
        [ 2.],
        [ 0.],
        [ 0.]])

In [17]:
torch.where(a!=-1)[0]

tensor([0, 2, 3, 5, 7, 8, 9])

In [23]:
transform = T.NormalizeFeatures()
data_dir = '../data/'
name = 'cora'
torch_dataset = Planetoid(root=f'{data_dir}Planetoid',
                            name=name, transform=transform)

In [26]:
data = torch_dataset[0]

In [28]:
data.train_mask

tensor([ True,  True,  True,  ..., False, False, False])

In [30]:
t = torch.tensor([True, False, True])

In [31]:
torch.where(t)

(tensor([0, 2]),)

In [34]:
d = data.x.shape[1]

In [35]:
d

1433

In [36]:
data.x.shape

torch.Size([2708, 1433])